# Generated by Django 4.1.5 on 2023-01-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_technologysubgroup_alter_technology_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.technologysubgroup'),
        ),
    ]
