# Generated by Django 4.1.5 on 2023-07-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_technology_subgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='technologysubgroup',
            name='technologies',
            field=models.ManyToManyField(to='portfolio.technology'),
        ),
    ]
